{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.funczz",
    "module": "rop-sam",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.funczz",
          "module": "rop",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "rop-sam-1.0.0.jar",
          "url": "rop-sam-1.0.0.jar",
          "size": 18180,
          "sha512": "f39467f1eec219c51eafb3fbd605298f8750977f95c2a68915fa9dd466979d40239a82bfb50f4694876ae3e0a944098447f217171ce2d4760d1cdbfebd338315",
          "sha256": "82384a6becce0aa23bc0ecae4e1d851a0ca26f13041dd1aec3bb19c626253dc0",
          "sha1": "4d49e5a3d07b67410f724e04304a10ec0612fbea",
          "md5": "0a0d13d0f30b9dd6426394edfd1f362c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.github.funczz",
          "module": "rop",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "rop-sam-1.0.0.jar",
          "url": "rop-sam-1.0.0.jar",
          "size": 18180,
          "sha512": "f39467f1eec219c51eafb3fbd605298f8750977f95c2a68915fa9dd466979d40239a82bfb50f4694876ae3e0a944098447f217171ce2d4760d1cdbfebd338315",
          "sha256": "82384a6becce0aa23bc0ecae4e1d851a0ca26f13041dd1aec3bb19c626253dc0",
          "sha1": "4d49e5a3d07b67410f724e04304a10ec0612fbea",
          "md5": "0a0d13d0f30b9dd6426394edfd1f362c"
        }
      ]
    }
  ]
}
